# Use an official Python runtime as a parent image
FROM python:3.7-slim

# Copy the current directory contents into the container at /wiki_trust
COPY wiki_trust_scripts/ ./wiki_trust/wiki_trust_scripts
Copy requirements.txt ./wiki_trust/

# Set the working directory to /wiki_trust
WORKDIR ./wiki_trust

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Define environment variable
ENV DBNAME=<database_name>
ENV DBHOST=<database_address>
ENV DBUSER=<database_user>
ENV DBPASSWORD=<database_password>
ENV AWSACCESSKEY=<aws_access_key>
ENV AWSSECRETKEY=<aws_secret_key>